### ISSUE TITLE
Viðbótarorð

### ISSUE THREAD

**Issue by torfason** [sveinbjornt/ensk.is#1]
Vil bara óska þér til hamingju með þetta frábæra framtak, og hvað þetta er vel útfært.

Nú finnast mjög mörg orð í bókinni eins og hún er í dag, en auðvitað ekki öll, og þá er spurning hvernig ný orð bætast við hana. Er markmiðið að hver sem er geti bætt við orðum, eða þá bent á orð sem vantar?

Ég leitaði til gamans að orðinu „econometrics“ en það vantar.

Fyrst datt manni í hug að safna bara saman öllum fyrirspurnum sem ekki finnast, en það er kannski ekki alveg það besta upp á information privacy notenda, spurning hvort það ætti að vera takki fyrir neðan „Engar niðurstöður fundust“ þar sem maður getur bent á orð sem vantar. Þá geta notendur líka lagt mat á hvort orðið eigi heima eða ekki (ef það var til dæmis bara innsláttarvilla). Svo væri svo hægt að safna þeim saman og ganga í að bæta mest umbeðnu orðunum við.

Eflaust ertu búinn að pæla í þessu öllu, en þá verður ekki hér annað en að ég fái að skrá fyrsta „issue“ við þessa snilld :-)

**Comment by sveinbjornt** [comment]
Takk! Eins og stendur er ég bara einn að bæta nýjum skilgreiningum við handvirkt, en með tíð og tíma er vonandi hægt að innlima einhvers konar lýðvirkjun í vefinn, þar sem notendur geta komið með uppástungur, leiðréttingar o.fl. og jafnvel "fuzzy" leit sem finnur orð þótt þau séu ekki 100% rétt skrifuð. Það mun svo væntanlega gleðja þig að orðið "econometrics" er nú komið inn í viðbótarlistann. :)

**Comment by judyfong** [comment]
svo er ég með áhuga að bæta veflesari - web reader á ensk.is vegna þess velthyding.is þýdda það sem veffimi svolitíð

**Comment by judyfong** [comment]
hér eru tveimur öðrum orð til að bæta við: haunt n. og indian giver https://www.quora.com/What-does-the-term-Indian-Giver-really-mean

**Comment by judyfong** [comment]
canteen
