### ISSUE TITLE
nit: button and input box don't match

### ISSUE THREAD

**Issue by hjonasson** [sveinbjornt/ensk.is#2]
Frábært verkefni! Áhugaverð þessi gamla orðabók og vel unnin hreinsun á stafsetningu og fleiru, þó sú gamla hefði kannski verið áhugaverð er þetta mun nothæfara. Bara til að bæta við einhverju má að mér sýnist eyða út [þessarri línu](https://github.com/sveinbjornt/ensk.is/blob/936155280c8cc51a0db2bfb670f8aae416f74bec/static/css/app.css#L76) og breyta þannig þessu

![image](https://user-images.githubusercontent.com/7723013/159221991-0eb17179-6382-49e7-9b87-7350a56b1279.png)

í þetta

![image](https://user-images.githubusercontent.com/7723013/159222026-b96117ca-96fc-458c-b777-f636a55fd69c.png)

(prófað í Firefox og Chrome). 

Má líka vel skrifast óþarft og eyða þessum miða.

**Comment by sveinbjornt** [comment]
Takk fyrir endurgjöfina, lagað í master.
