### ISSUE TITLE
Missing data file for gen.py script

### ISSUE THREAD

**Issue by egillian1** [sveinbjornt/ensk.is#3]
Hello,
Running `python gen.py` within a python virtual environment with the required packages installed gives the following output:

```
python gen.py 
Traceback (most recent call last):
  File "gen.py", line 127, in <module>
    entries = read_all_entries()
  File "gen.py", line 63, in read_all_entries
    pn = page_for_word(w)
  File "/home/ian/forrit/ensk.is/util.py", line 141, in page_for_word
    with open("data/word2page.json", "r") as file:
FileNotFoundError: [Errno 2] No such file or directory: 'data/word2page.json'
```
I couldn't find a way to generate the file with a quick look through the scripts, but may well have missed something.

(Ákvað að hafa þetta á ensku svo sem flestir gætu skilið, en ég get breytt því ef íslenskan er ákjósanlegri)

**Comment by sveinbjornt** [comment]
Takk fyrir ábendinguna, lagað.
