### ISSUE TITLE
Icelandic to english dictionary

### ISSUE THREAD

**Issue by judyfong** [sveinbjornt/ensk.is#6]
Hi, is there any interest in creating an icelandic to english dictionary with the information provided here on ensk.is? essentially a dictionary that is reversible both ways. The icelandic entries will arguably be less rich than the english since they will just be an icelandic definition referring back to an english keyword but still extremely valuable

**Comment by judyfong** [comment]
It is written in python so if it is done in this way at all (I have not looked at the code), then something like this should be possible: https://stackoverflow.com/questions/42438808/finding-all-the-keys-with-the-same-value-in-a-python-dictionary

**Comment by sveinbjornt** [comment]
Árnastofnun is working on an Icelandic-English dictionary which should be out soon.

**Comment by judyfong** [comment]
Oh cool. What I liked about this dictionary and adding the ice-en version to it is that it's on github so it's open to contributors theoretically, the codebase is also visible, everything is linked already.

Because a major drawback of arnastofnun's dictionary and other services is how clunky it is, that it's ultimately curated by a very small selection of people. **The upside is amazing quality.** The downside is that words take a long time to appear in the dictionary and perfectly normal common words (any word that an educated icelander would know) are not put in there because they're infrequent or compound words or both. So as a native english speaker used to finding every word under the sun in the many dictionaries available, I've found the Icelandic dictionary experience very limiting.

So to me a dictionary made by experts does not sufficiently cover the dictionary experience I am interested in. I am willing to hold out hope for it but... I've often times already taken matters in my own hands by curating my own dictionary https://projects.judyyfong.xyz/dictionary/ but I'd prefer to give back to a more open one.

**Comment by sveinbjornt** [comment]
I have given some thought to OCR-ing Zoega's Icelandic-English dictionary, but the truth is that the English-Icelandic one has been so much editorial work, quite apart from fixes and additions, that I do not feel up to repeating the experience. If you want to give it a shot, go for it!
